### ISSUE TITLE
Split out binaries for each engine

### ISSUE THREAD

**Issue by emschwartz** [interledger-rs/settlement-engines#4]
Instead of having an `interledger-settlement-engines` binary, there should be a separate binary for each Settlement Engin

**Comment by gakonst** [comment]
Plan after discussion is:

We move `interledger-settlement` in this repository, rename the repo to `interledger-settlement`, identify common traits and move them to `settlement-core` and have a separate subcrate and binary for each engine implementation, with the API living in a `settlement-api` crate.
